"""Initial migration

Revision ID: a2090d9d40fe
Revises: 
Create Date: 2023-07-15 00:34:08.763745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2090d9d40fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('playlist_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'songs', 'playlists', ['playlist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'songs', type_='foreignkey')
    op.drop_column('songs', 'playlist_id')
    # ### end Alembic commands ###
